spring.application.name=shortlink

spring.datasource.url=jdbc:postgresql://localhost:5432/shortlink_db
spring.datasource.username=postgres
spring.datasource.password=pass1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true

app.base-url=http://localhost:8080

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
app.cache.links-ttl-minutes=${APP_CACHE_LINKS_TTL_MINUTES:10}