spring.application.name=shortlink

spring.datasource.url=jdbc:postgresql://localhost:5432/shortlink_db
spring.datasource.username=postgres
spring.datasource.password=pass1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true

app.base-url=http://localhost:8080